# Generated by Django 3.1 on 2020-08-25 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller_orders_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorders',
            name='cancelation_reason',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='cancelation_status',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('659b1df5-024c-4329-8e59-3cfe31e1c2db'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='invoice_danfe_url',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellerorders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
