# Generated by Django 3.1 on 2020-08-26 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller_orders_api', '0002_auto_20200825_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a2381c7-c436-4a01-9a92-3e0fb9a97c02'), editable=False, primary_key=True, serialize=False),
        ),
    ]
